### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by shubham-kaushal** [numldesign/numl-react#1]
Setup CI/CD Github Actions & Apps with 
- [x] StorybookJs
- [x] Chromatic
- [x] React Testing Library
- [x] CodeSandbox https://codesandbox.io/docs/ci
- [x] Auto publish npm package https://github.com/marketplace/actions/publish-to-npm

**Comment by SyedUmerHasan** [comment]
All CI/CD completed. 
So I am closing this issue.
