### ISSUE TITLE
ATOMS

### ISSUE THREAD

**Issue by shubham-kaushal** [numldesign/numl-react#3]
- [x] Avatar
- [x] Badge
- [x] Buttons
- [x] Button Groups
- [x] Checkboxes
- [x] Chips
- [x] Exception List
- [x] Footer Help
- [x] Footer
- [x] Links
- [x] Message Error
- [x] Pagination & Icon Button
- [x] Progress Bar
- [x] Radio Buttons
- [x] Range Slider
- [x] Switches
- [x] Tags
- [x] Text Inputs
- [x] Thumbnails

**Comment by SyedUmerHasan** [comment]
Atoms component has been completed, so I am closing this issue. 
In case refactoring needed, I will open another issue.
